spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: brunolopes
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      generate-ddl: true
      hibernate:
        ddl-auto: drop-create
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
        defaultSchema: public
        hbm2ddl:
          method: update
        show_sql: true
        format_sql: true
        connection:
          provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

# JWT Auth
auth:
  secret: some-random-secret
  expires: 604800
  header: Authorization 

# keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: xe4vvhv9
    keyStoreType: PKCS12
    keyAlias: tomcat
    